"""Create country table

Revision ID: 530725bb554e
Revises: 
Create Date: 2024-03-04 20:02:38.758299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530725bb554e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('iso_alpha2', sa.String(length=2), nullable=False),
    sa.Column('iso_alpha3', sa.String(length=3), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('phone_code', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('iso_alpha2'),
    sa.UniqueConstraint('iso_alpha2'),
    sa.UniqueConstraint('iso_alpha3')
    )
    op.create_table('jwt_token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jwt_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('jwt_auth_active', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=64), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=False),
    sa.Column('country_iso2', sa.String(length=2), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('field_of_study', sa.String(length=64), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_iso2'], ['country.iso_alpha2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('country_iso2', sa.String(length=2), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('position_title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['country_iso2'], ['country.iso_alpha2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('certification')
    op.drop_table('users')
    op.drop_table('jwt_token_blocklist')
    op.drop_table('country')
    # ### end Alembic commands ###
