version: '3.7'

services:

  react-berry:
    container_name: react-berry
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  nginx-front:
    image: nginx:latest
    ports:
      - 80:80 # Standard HTTP
    volumes:
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - react-berry 
